### ISSUE TITLE
Hi, I would like to ask why this problem occurs, is it a code problem? How to solve it? 

### ISSUE THREAD

**Issue by Daranan** [ChatAFLndss/ChatAFL#10]
![屏幕截图 2024-08-05 175130](https://github.com/user-attachments/assets/58edaaa7-635c-462a-928a-4e2235d0cc24)

**Comment by Marti2203** [comment]
Hi,
This looks like an issue with processing the model response. Have you tried reproducing it with other subjects?

**Comment by Daranan** [comment]
yeah,I tried on multiple subjects such as kamailio, lightftp, etc., and the model I used was llama3, is it the model's problem?

**Comment by Marti2203** [comment]
Likely, the model's output is not in the correct format after you mentioned that you are not using OpenAI's models
