### ISSUE TITLE
Hi, I wonder how you "ask" the LLM to do things? What part of code can I use to ask the chatgpt to do things like add seeds or cover new state?

### ISSUE THREAD

**Issue by noname4X4** [ChatAFLndss/ChatAFL#11]

**Comment by Marti2203** [comment]
Hi,
The file [chat-llm.c](https://github.com/ChatAFLndss/ChatAFL/blob/master/ChatAFL/chat-llm.c) contains the web API calls to openAI's models. You can search in afl-fuzz.c for invocations of the methods there.
