### ISSUE TITLE
Reproduction Failed

### ISSUE THREAD

**Issue by 5angjun** [ChatAFLndss/ChatAFL#13]
Hello, I'm sangjun who is interested in your project.

I try to reproduce your project, however, there are some issue related to analyze the gcov result for graph.

This is my result after fuzzed with `./run.sh 5 240 kamailio,pure-ftpd,live555 chatafl,aflnet`.
![스크린샷, 2024-08-28 21-04-46](https://github.com/user-attachments/assets/6a3418c2-aae5-4de0-b1b9-f7f7a49f36f7)

But i have stucked with next stage.
`./analyze.sh live555 240`
![스크린샷, 2024-08-28 21-06-23](https://github.com/user-attachments/assets/23ca26ab-1406-44f0-b6c6-468c807de2e3)

I think the problem comes from difference of package version or python version that used in `home/sangjun/ChatAFL/benchmark/scripts/analysis/profuzzbench_plot.py`

my spec is 
python3.8.10
Ubuntu 20.04.6 LTS 
![스크린샷, 2024-08-28 21-09-28](https://github.com/user-attachments/assets/9c016fce-05e3-48d7-9bc0-a476a69e3509)

Can you check given script can reproducable again??

**Comment by Marti2203** [comment]
Hi, the issue is related to the Pandas library.  You are probably using a too recent version of the library to execute the script and the APIs have changed. Can you try installing an older version (possibly 2.1.3, by doing `pip install pandas==2.1.3` as I see it is from November last year)?

**Comment by 5angjun** [comment]
your right!

It works in Pandas Version: 1.2.5.

Thanks!!

```
sangjun@sangjunLab:~/ChatAFL$ pip3 install pandas==3.0.0
ERROR: Could not find a version that satisfies the requirement pandas==3.0.0 (from versions: 0.1, 0.2, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.6.0, 0.6.1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.16.2, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 0.19.2, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.21.0, 0.21.1, 0.22.0, 0.23.0, 0.23.1, 0.23.2, 0.23.3, 0.23.4, 0.24.0, 0.24.1, 0.24.2, 0.25.0, 0.25.1, 0.25.2, 0.25.3, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.4.0rc0, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.5.0rc0, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 2.0.0rc0, 2.0.0rc1, 2.0.0, 2.0.1, 2.0.2, 2.0.3)

```
