### ISSUE TITLE
json_object_array_get_idx: Assertion `json_object_get_type(jso) == json_type_array' failed.

### ISSUE THREAD

**Issue by Blair-Cheng** [ChatAFLndss/ChatAFL#2]
Hi, I am having "json_object_array_get_idx: Assertion `json_object_get_type(jso) == json_type_array' failed." problem while using CHATAFL for live555. " problem, what is the cause of this and what is the solution? Looking forward to your answer thanks!
![image](https://github.com/ChatAFLndss/ChatAFL/assets/143257756/77fa26bf-28e3-4c01-bfc4-ced531e6ed38)

**Comment by CAPCOMIN** [comment]
Hello, I also encountered this problem. How did you solve it? Thank you.

**Comment by Daranan** [comment]
Hi,did you solve that json problem?Could you tell me the solution?Thank you very much.
