### ISSUE TITLE
PROGRAM ABORT 

### ISSUE THREAD

**Issue by Blair-Cheng** [ChatAFLndss/ChatAFL#3]
Hello, I cannot run ChatAFL successfully, the problem is as follows:
![image](https://github.com/ChatAFLndss/ChatAFL/assets/143257756/19ac562c-6961-4d1e-b1cc-094a6a9e73ab)

[-] PROGRAM ABORT : Test case 'id:000000,orig:enriched_0_rtsp_requests_aac.raw' results in a crash
 Location : perform_dry_run(), afl-fuzz.c:4363
The test case attachment is here
[enriched_0_rtsp_requests_aac.zip](https://github.com/ChatAFLndss/ChatAFL/files/14009438/enriched_0_rtsp_requests_aac.zip)
What is the cause of this problem and how to solve it? Sometimes seed files can also cause this problem. Looking forward to your reply.

**Comment by Marti2203** [comment]
Hi @Blair-Cheng can you provide a little more context about this issue? I have just tried reproducing it on live.2023.05.10  and could not crash the fuzzer as you have shown in the image.

**Comment by Marti2203** [comment]
Hi, this issue has been open for some time and I will consider it stale, so will close it. If you are still experiencing this issue, do reopen it. Thank you!
