### ISSUE TITLE
When running the enrich_testcases method, it's possible to encounter a situation where the number of tokens exceeds the max_tokens limit.

### ISSUE THREAD

**Issue by wzk2239115** [ChatAFLndss/ChatAFL#6]
<img width="918" alt="屏幕截图 2024-04-29 150424" src="https://github.com/ChatAFLndss/ChatAFL/assets/166099643/d79d66bb-8758-4fc8-8c53-a338b605307f">

**Comment by 18893007124** [comment]
I'm also encountering this issue. Has it been resolved now?

**Comment by 18893007124** [comment]
I haven't used it before. Could you please tell me where this branch is?
