### ISSUE TITLE
The reproduction confirmation.

### ISSUE THREAD

**Issue by adcf3016** [ChatAFLndss/ChatAFL#9]
Recently, I have been trying to reproduce your results and encountered a few issues:

After using it for a period of time, the number of OpenAI tokens does not change anymore (assuming it is set for one hour, the token count stops changing around 40 to 50 minutes). I would like to ask if this is normal.

Below are the results of executing ./run.sh 5 60 forker-daapd chatafl. In other reproductions, I encounter almost the same results. I would like to ask if it is normal that the subsequent coverage does not increase.
![cov_over_time_forked-daapd](https://github.com/user-attachments/assets/bc05c3bd-0db8-448b-b819-be33a5238cfc)
![state_over_time_forked-daapd](https://github.com/user-attachments/assets/e9771402-47b9-476b-a0b9-b378ed65a162)

Thank you very much for taking the time to reply.

**Comment by Marti2203** [comment]
Hi,
The reason for this is that the fuzzer by default has been set to have a maximum amount of calls to the LLM when a coverage plateau. We have limited this with the variable `CHATTING_THRESHOLD`. You can increase it to change the expected behavior.
